In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
X = np.array([-4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0], dtype=float)
Y = np.array([5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, ], dtype=float)

In [ ]:
model=tf.keras.Sequential([tf.keras.layers.Dense(units=1,input_shape=[1])])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(optimizer='sgd',loss='mean_squared_error')

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 1)                   │               2 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X,Y,epochs=30)

Epoch 1/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 278ms/step - loss: 101.6818
Epoch 2/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 90.9417
Epoch 3/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 82.7502
Epoch 4/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 76.3425
Epoch 5/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 71.1912
Epoch 6/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 66.9326
Epoch 7/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 63.3155
Epoch 8/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 60.1658
Epoch 9/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 57.3631
Epoch 10/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 54.8233
Epoch 11/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 52.4878
Epoch 12/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 50.3154
Epoch 13/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 48.2768
Epoch 14/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 46.3512
Epoch 15/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 44.5232
Epoch 16/30
1/1 ━

In [ ]:
import numpy as np  # Import NumPy for array manipulation

# Convert the list to a NumPy array
input_data = np.array([-2.0, 10.0]).reshape(-1, 1)

# Now use the array for prediction
predictions = model.predict(input_data)

print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[[ 1.4083493]
 [17.27378  ]]


In [ ]:
import numpy as np
import tensorflow as tf

# Sample input data for classification
X = np.array([-4.0, -3.0, -2.0, -1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0], dtype=float)
Y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int)

# Reshape the input data to comply with the model's input shape
X = X.reshape(-1, 1)




In [ ]:
X

array([[-4.],
       [-3.],
       [-2.],
       [-1.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.]])

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=1, input_shape=[1], activation='sigmoid')  # Sigmoid activation for binary classification
])

model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X, Y, epochs=10)

# Assuming you wish to make predictions after training
predictions = model.predict(X)

Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 460ms/step - accuracy: 0.9000 - loss: 0.1803
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 1.0000 - loss: 0.1800
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.1797
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.1794
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 1.0000 - loss: 0.1791
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.1789
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.1786
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.1783
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 1.0000 - loss: 0.1780
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.1777
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


In [ ]:
predictions

array([[0.02124072],
       [0.05358009],
       [0.12868325],
       [0.2781223 ],
       [0.5012656 ],
       [0.7239058 ],
       [0.8724477 ],
       [0.946931  ],
       [0.97896874],
       [0.99183214]], dtype=float32)