In [ ]:
import numpy as np

numpy.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)

- object : Objek apa pun yang mengekspos metode antarmuka array mengembalikan array, atau apa pun (bersarang) urutan
- dtype  : type data, opsional
- copy   : Opsional. Secara default (True), objek disalin
- order  : C (baris mayor) atau F (utama kolom) atau A (apa saja) (default)
- subok  : Secara default, array yang dikembalikan dipaksa menjadi array kelas dasar. Jika benar, sub-kelas akan diberikan
- ndimin : Menentukan dimensi minimum dari array yang dihasilkan

In [ ]:
#memasukan nilai integer atau nilai dengan tipe data apapun sesuai ebutuhan
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
#memanggil nilai index 3
arr[3]

4

In [ ]:
#contoh array 2 dimensi
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


Tipe Data Array

In [ ]:
print(a.dtype)

int64


In [ ]:
#contoh 2 tipe data dengan unicode string
arr_1=np.array(['Rizki','Ramdani','Massa Sih'])
print(arr_1.dtype)


<U9


In [ ]:
#tipe data yang didefinisikan
arr_2=np.array([1,2,3,4],dtype='S')
print(arr_2)
print(arr_2.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
# contoh tipe data yang diubah
arr_3=np.array([1.2,1.3,2.5])
arr=arr_3.astype('i')
print(arr)
print(arr.dtype)

[1 1 2]
int32


In [ ]:
#konversi lit menjadi ndarray
x=[1,2,3,4,5]
print(type(x))
x=np.asarray(x)
print(x.dtype)
print(x)

<class 'list'>
int64
[1 2 3 4 5]


In [ ]:
#konversi list menjadi array dengan tipe data yang didefinisikan
x=[1,2,3,4,5,6,7,8]
print(type(x))
x=np.asarray(x,dtype='f')
print(x.dtype)
print(x)

<class 'list'>
float32
[1. 2. 3. 4. 5. 6. 7. 8.]


Membuat rentang nilai menggunakan numpy (STUDY CASE) :
membuat dataframe menggunakan rentang nilai random dan deterministik



numpy.arange(start, stop, step, dtype)

In [ ]:
a=np.arange(0,2,0.2,dtype='f')
x=np.arange(1,11,1)
y=np.arange(10,20,1)
print(a)
print(x)
print(y)

[0.        0.2       0.4       0.6       0.8       1.        1.2
 1.4       1.6       1.8000001]
[ 1  2  3  4  5  6  7  8  9 10]
[10 11 12 13 14 15 16 17 18 19]


In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame({'a':a,'x':x,'y':y})

a   x   y
0  0.0   1  10
1  0.2   2  11
2  0.4   3  12
3  0.6   4  13
4  0.8   5  14
5  1.0   6  15
6  1.2   7  16
7  1.4   8  17
8  1.6   9  18
9  1.8  10  19

In [ ]:
#membuat array dengan nilai 1 di numpy
x=np.ones((4,5))#baris,kolom
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#membuat array dengan nilai 0 di numpy
x=np.zeros((5,6))
print(x)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
#custom
y=np.full((3,4,),67)
print(y)

[[67 67 67 67]
 [67 67 67 67]
 [67 67 67 67]]


In [ ]:
z=np.random.rand(12,3)
print(z)

[[0.72663044 0.57052644 0.45768123]
 [0.63520974 0.94686787 0.94551167]
 [0.70410202 0.01562266 0.44528124]
 [0.11571826 0.83074756 0.59825907]
 [0.9703679  0.86557279 0.70290169]
 [0.99233389 0.51052366 0.9815155 ]
 [0.24742053 0.73076907 0.78397334]
 [0.51934964 0.48879254 0.9161104 ]
 [0.69885532 0.12076093 0.76470988]
 [0.74479348 0.31835653 0.16527432]
 [0.86140128 0.69718339 0.73336894]
 [0.96224319 0.78591522 0.32172222]]


In [ ]:
pd.DataFrame(z,columns=['z','x','a'])

z         x         a
0   0.726630  0.570526  0.457681
1   0.635210  0.946868  0.945512
2   0.704102  0.015623  0.445281
3   0.115718  0.830748  0.598259
4   0.970368  0.865573  0.702902
5   0.992334  0.510524  0.981516
6   0.247421  0.730769  0.783973
7   0.519350  0.488793  0.916110
8   0.698855  0.120761  0.764710
9   0.744793  0.318357  0.165274
10  0.861401  0.697183  0.733369
11  0.962243  0.785915  0.321722